import xlsxwriter


class ExcelReport:

    def __init__(self, file_name):
        self.workbook = xlsxwriter.Workbook(file_name)
        self.workbook.set_properties({
            'title': "Crafted Beer analysis",
            'subject': 'Documentation',
            'author': 'Rafael Lopez',
            'company': 'ITESM',
            'category': 'Documentation',
            'keywords': 'beer',
            'comments': 'Autogenerated File by Python 2.7'})

        return

    def features_worksheet(self):
        worksheet = self.workbook.add_worksheet("Features")
        worksheet.write('A1', "Feature Analysis for the beers")
        worksheet.insert_image('B2', "../Results/Crafted-beer-style-piechart.png")
        worksheet.insert_image('E2', "../Results/Crafted-beer-style-hist.png")
        return

    def close_report(self):
        self.workbook.close()
        return